### ISSUE TITLE
Download with JD always shows failed

### ISSUE THREAD

**Issue by speedy80** [piejanssens/premiumizer#69] opened 2017-02-08 09:46 UTC
I'm downloading from premiumizer with JD. The files get downloaded after assigning a category. But at the end I always get in the log following error:
ERROR : JD did not return package status for: "some download"

In the history tab therefore all download have the status failed. Is this a bug or could it be a missing setup on my side?

Really appreciate you help and work!

**Comment by neox387** [comment] 2017-02-08 12:03
Ok so this should happen ?:

1. the files get added in linkgrabber in Jdownloader after assigning a category in premiumzer
2. files start downloading after few seconds
3. premiumizer reports the progress of the download on home screen
4. when download is finished/successful the files get removed from Jdownloader download screen

You are not manually deleting finished links from Jdownloader or closing Jdownloader right before it ends in error ?

In premiumizer the progress is near 100% finished before you get the error ?

You are not getting JD returned failed for as final error ?

You are using Jdownloader 2 fairly updated right ? :)
In Jdownloader settings -- general -- Remove finished downloads is set to never ?

**Comment by speedy80** [comment] 2017-02-09 12:25
I can confirm steps 1 - 3. 


I'm not deleting any links in Jdownloader 2 manually or closing Jdownloader. Normally the progress in premiumizer is at 99.5% when the error occurs.

Point 4: files do not get removed.



Jdownloader 2 is up-to-date. What I checked is the JD settings an regarding the automatic deleting. They were not set to "never". 

I changed this setting and tried a new download. Now progress goes to 100% but does not remove the download from JD2 and stays at 100% (now for a couple of hours already. No log file entries after "Downloading: xy".





-----Ursprüngliche Nachricht-----
Von: neox387 <notifications@github.com>
Gesendet: Mit 8 Februar 2017 13:04
An: piejanssens/premiumizer <premiumizer@noreply.github.com>
CC: Patrick Caminada <patrick@caminada.cc>; Author <author@noreply.github.com>
Betreff: Re: [piejanssens/premiumizer] Download with JD always shows failed (#69)

Ok so this should happen ?:

1.	the files get added in linkgrabber in Jdownloader after assigning a category in premiumzer
2.	files start downloading after few seconds
3.	premiumizer reports the progress of the download on home screen
4.	when download is finished/successful the files get removed from Jdownloader download screen

You are not manually deleting finished links from Jdownloader or closing Jdownloader right before it ends in error ?

In premiumizer the progress is near 100% finished before you get the error ?

You are not getting JD returned failed for as final error ?

You are using Jdownloader 2 fairly updated right ? :)
 In Jdownloader settings -- general -- Remove finished downloads is set to never ?

**Comment by neox387** [comment] 2017-02-09 21:55
But it needs to be set to never because premiumizer will remove the link if it gets back that the status is finished, would have to run it trough a debugger to figure out where the problem is ..

I'm using the 2 for ages & don't have this problem =(

**Comment by neox387** [comment] 2017-09-11 12:44
@speedy80 still having issues with latest version ?

**Closed** 2017-12-13 15:57 UTC
