### ISSUE TITLE
Downloads are "hanging"

### ISSUE THREAD

**Issue by anonvoy** [piejanssens/premiumizer#51] opened 2016-09-02 19:20 UTC
Thanks for this software, which is amazing when it works. Unfortunately, something does not always work for me, and that is downloading files from the cloud using the built-in downloader. I don't know if this is an appropriate "issue" for this place, but I'll just try it.

I run premiumizer on Linux, using a virtual environment. All the requirements are met, as pip tells me. I use premiumize only for torrents, to supplement my main nzb setup, which is of the sabnzbd/sickrage/couchpotato variety. So I don't have many files for which I use premiumizer, and I've only installed it yesterday too. 

Everything else besides downloading works fine, I can access the web interface, change settings etc.; having couchpotato and sickrage add torrents to the cloud via premiumizer also works fine.

I've seen premiumizer download torrents from the cloud as expected, run nzbToMedia with good results, and autodelete the torrent from the cloud. In short, everything working as it should. But for several torrents now, I see downloads kind of stalling. Which also means nzbToMedia is not called, and processing does not go forward.

In these cases, the download begins, and the torrent is shown as being downloaded to the computer, but the download process is not completed. The download progress, shown in %, may remain at 0 % or may stall at 11,5 %, 99,5 %, 99,6 % or 99,9 %. Files **are** being downloaded, but sometimes not all of them. Let's say there is a mkv, a txt and a nfo file in the torrent; I've had the txt and nfo downloaded, but not the mkv, download progress was shown to be 0 %.  Or, a torrent with 10 mkv files. 2 mkv files are downloaded to the correct directory on my hard disk (complete files, not partial ones), but the rest are not. Download progress stalls at 10,8 %.

Another example: Torrent with main mkv, sample mkv and txt. Main mkv and txt are downloaded, sample mkv is not (not downloading samples is what I have in the category settings, so it is expected behavior). Download progress is shown to be 0 bytes of 1.42 GB. And one last example: Torrent has main avi, sample avi, one nfo and one txt file. nfo and txt are downloaded, the avis are not downloaded. Download progress is shown as 0 bytes of 1.37 GB.

Waiting does not help, the stalled downloads will not go forward. The only option is to stop the downloads.

Any idea what is the problem here? I've looked at the logs and debug logs, but I see nothing there that could explain that behavior. I could supply some if you think theyre'helpful.

**Comment by neox387** [comment] 2016-09-02 19:45
Need to wait for pull request to get merged, last merge 4 days ago I changed a lot of things & something was broken.

So once merged update from settings page

**Comment by piejanssens** [comment] 2016-09-05 08:57
@anonvoy Please pull in the latest version and report back.

**Comment by anonvoy** [comment] 2016-09-05 12:12
I did upgrade to the latest version, and now premiumizer can't even connect to premiumize.me. It's stuck on the turning wheel with "Loading Download Tasks".

Additionally, trying to access "Log" or "History" gives me an "Internal Server Error". Running in bash i get this:

(virtualenv)abc@linux-dars:~/.premiumizer> python Premiumizer.py                    
------------------------------------------------------------------------------------------------------------
|                                                                                                           |
-------------------------------------------WELCOME TO PREMIUMIZER-------------------------------------------
|                                                                                                           |
------------------------------------------------------------------------------------------------------------
09-05 14:08:54: INFO : -------------------------------------------------------------------------------------
09-05 14:08:54: INFO : -------------------------------------------------------------------------------------
09-05 14:08:54: INFO : -------------------------------------------------------------------------------------
09-05 14:08:54: INFO : Logger Initialized
09-05 14:08:54: INFO : Logfile Initialized
09-05 14:08:54: INFO : Running at /home/abc/.premiumizer
09-05 14:08:54: INFO : Watchdir is enabled at: /home/abc/Downloads/blackhole/
09-05 14:08:54: INFO : Starting server on 127.0.0.1:5001 
09-05 14:08:56: INFO : Initializing watchdog complete
Client says hello!
Client disconnected
[2016-09-05 14:09:07,158] ERROR in app: Exception on /history [GET]
Traceback (most recent call last):
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/flask_login.py", line 789, in decorated_view
    return func(*args, **kwargs)
  File "Premiumizer.py", line 1228, in history
    return render_template("history.html", taskad=taskad, taskdel=taskdel, taskdl=taskdl)
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/abc/.premiumizer/templates/history.html", line 2, in top-level template code
    {% set active_page = "history" %}
  File "/home/abc/.premiumizer/templates/base.html", line 60, in top-level template code
    {% block content %}
  File "/home/abc/.premiumizer/templates/history.html", line 11, in block "content"
    <pre>{{ taskdel }}</pre>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2465: ordinal not in range(128)

**Comment by neox387** [comment] 2016-09-05 13:40
Try to delete the 2 log files and restart, should fix above error I think

**Comment by anonvoy** [comment] 2016-09-05 13:48
It did, thanks. Still not connecting to premiumize.me though.

One more observation on the original error: I tried several torrents yesterday. Premiumizer did successfully download some, call postprocessing etc., and all of those had just 1 file in the torrent. So it seems the problem is with torrents that contain more files than just 1.

**Comment by neox387** [comment] 2016-09-05 13:55
i'm installing ubuntu in a vm to test, mine is connecting fine on windows ..

**Comment by neox387** [comment] 2016-09-05 14:38
working fine on new ubuntu with firefox, just the restart not working should work after next pr

**Comment by anonvoy** [comment] 2016-09-05 14:54
Still no connection to premiumize.me on my setup, which is OpenSuse 13.2. I just re-entered my premiumize.me account data into premiumizer to make sure. The connection worked fine until I updated premiumizer earlier today.

**Comment by neox387** [comment] 2016-09-05 14:59
and your requirements are up to date ? if you did a git pull instead of updating trough settings it will not update the requirements, or at least it should, I have not tested if upgrading requirements works on linux ..  :)


Do u get any error like
`Cannot connect to premiumize.me. Check your premiumize account details in settings and if premiumize.me is up`

or something in the debuglog ? 

It might connect fine but browser just refusing something try F12 for browser debug .. ?

**Comment by anonvoy** [comment] 2016-09-05 15:04
My browser of choice is Firefox, and I haven't changed any browser settings when updating premiumizer. It worked before, it doesn't now. It also doesn't work in Chrome. Opera, Vivaldi, Konqueror.

Just enabled the debug log, what I get is this over and over again:

09-05 17:01:15       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-05 17:01:15       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2016-09-05 17:01:16.755660+02:00 (in 0.999082 seconds)
09-05 17:01:15       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2016-09-05 17:01:16 CEST)" (scheduled at 2016-09-05 17:01:15.755660+02:00)
09-05 17:01:15       root                                     : DEBUG    : def update started
09-05 17:01:15       root                                     : DEBUG    : def prem_connection started
09-05 17:01:15       requests.packages.urllib3.connectionpool : DEBUG    : "POST /api/transfer/list HTTP/1.1" 200 None
09-05 17:01:15       root                                     : DEBUG    : def parse_task started
09-05 17:01:15       root                                     : DEBUG    : def get_task started
09-05 17:01:15       apscheduler.executors.default            : ERROR    : Job "update (trigger: interval[0:00:01], next run at: 2016-09-05 17:01:16 CEST)" raised an exception
Traceback (most recent call last):
  File "/home/abc/.premiumizer/virtualenv/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/abc/.premiumizer/premiumizer.py", line 892, in update
    idle = parse_tasks(transfers)
  File "/home/abc/.premiumizer/premiumizer.py", line 940, in parse_tasks
    size=size + ' --- ', speed=speed + ' --- ', eta=eta)
  File "/home/abc/.premiumizer/DownloadTask.py", line 62, in update
    self.callback('update_task', {'task': self.get_json()})
  File "/home/abc/.premiumizer/DownloadTask.py", line 81, in get_json
    return {'progress': self.progress, 'speed': self.speed, 'dlsize': self.dlsize, 'eta': self.eta, 'hash': self.hash,
AttributeError: DownloadTask instance has no attribute 'dlsize'
09-05 17:01:16       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
09-05 17:01:16       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
09-05 17:01:16       geventwebsocket.handler                  : DEBUG    : Can only upgrade connection if using GET method.

This is repeated constantly.

**Comment by anonvoy** [comment] 2016-09-05 15:16
Requirements are up to date:

```
(virtualenv)abc@linux-dars:~/.premiumizer> pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): watchdog==0.8.3 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): APScheduler==3.2.0 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): greenlet==0.4.10 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): bencode==1.0 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): chardet==2.3.0 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): futures==3.0.5 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): python-engineio==1.0.1 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): flask-apscheduler==1.4.0 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): flask-socketio==2.7.0 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): flask-login==0.3.2 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): flask-compress==1.3.0 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): flask-reverse-proxy==0.2.0.2 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): gevent-websocket==0.9.5 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): jinja2==2.8 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): pathtools==0.1.2 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): PySmartDL from https://github.com/neox387/pySmartDL/archive/1.2.5.zip in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): requests==2.11.1 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): python-socketio==1.5.0 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): tzlocal==1.2.2 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): werkzeug==0.11.11 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): gevent==1.1.2 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.5.3 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied (use --upgrade to upgrade): pycrypto==2.6.1 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 28))
Requirement already satisfied (use --upgrade to upgrade): myjdapi==1.0.1 in ./virtualenv/lib/python2.7/site-packages (from -r requirements.txt (line 29))
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in ./virtualenv/lib/python2.7/site-packages (from watchdog==0.8.3->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in ./virtualenv/lib/python2.7/site-packages (from watchdog==0.8.3->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pytz in ./virtualenv/lib/python2.7/site-packages (from tzlocal==1.2.2->-r requirements.txt (line 22))
Cleaning up...
```

I also don't get any error message like "Cannot connect to premiumize.me. Check your premiumize account details in settings and if premiumize.me is up" in the dbug log.

**Comment by neox387** [comment] 2016-09-05 16:30
this is very weird, do you still have torrents in the cloud ? this might be because u have the same torrent before the update & after, & now it looks for dlsize but if it's in database before the update it wont have dlsize in there

**Comment by anonvoy** [comment] 2016-09-05 16:53
Yes, I did have some torrents still in the cloud. I deleted them from the cloud, restarted premiumizer, and it could connect to premiumize.me. Adding torrents again works, and downloading them works too, including the multifile torrents which were "hanging" before (the original problem).

So it seems everything is working now as it should. Thanks for your work and advice. And I hope helping me was not a complete waste of time for you :-)

**Comment by piejanssens** [comment] 2016-09-05 17:23
@neox387 Do you have an idea what went wrong here? We should make sure that people don't get stuck in this situation..

**Comment by neox387** [comment] 2016-09-05 17:55
1) 
some weird ascii character caused by traceback or something in a log file creates another error because the log file get's read at line 1218 & 1372 & fla

2)
because i changed attribute in downloadtask.py and a old task in the database file did not have this new attribute

**Comment by neox387** [comment] 2016-09-05 18:17
@anonvoy NP, and it's good to have feedback so report further problems / ideas you might have ^^

**Comment by PremiumizeNZB** [comment] 2016-09-08 15:51
> this is very weird, do you still have torrents in the cloud ?
I have the same problem, stuck at "Loading Download Tasks".
I can't delete my Torrents via Premiumize because I still need them (they do not exist anymore, I have them as a backup in the Premiumize Cloud).

**Comment by neox387** [comment] 2016-09-08 19:15
Noop it's something that's not updated much

**Comment by neox387** [comment] 2017-09-11 12:43
@anonvoy still having issues with latest version ? :)

**Comment by anonvoy** [comment] 2017-09-12 17:52
@neox387 Nope, can't remember any problems for some time. If something comes up, I'll let you know :-)

**Closed** 2017-09-14 13:53 UTC
