### ISSUE TITLE
Cannot make subdirs more than 1 level deep

### ISSUE THREAD

**Issue by 03184** [piejanssens/premiumizer#246] opened 2020-03-06 22:01 UTC
Using latest premiumizer with docker, main folder is /downloads with sub directories /tv /movies /default.
editing settings.cfg manually, when making a series category in the sub dir /tv for example 
cat_name[3] = Bones
cat_dir[3] = /downloads/tv/Bones
saving and restarting premiumizer removes the /tv/ dir so it ends up as:
cat_name[3] = Bones
cat_dir[3] = /downloads/Bones.

I have notice by not entering a cat_name keeps the cat_dir correctly but obviously category does not show in the gui

**Comment by neox387** [comment] 2020-04-17 11:18
cannot reproduce this on windows

**Comment by dbroome1978** [comment] 2020-12-02 02:51
I have the same issue.  It's annoying because I store my movies and tv shows on different hardrives.  I'd prefer they would download to the correct harddrive

**Comment by neox387** [comment] 2021-01-09 17:49
Still have this issue with latest build it might have been fixed with #275

**Closed** 2021-03-18 18:13 UTC
Labels: wontfix
